[package]
name = "sessiond-dhall-proc-macros"
# remember to update html_root_url
version = "2.0.0"
authors = ["Nadrieril <nadrieril@users.noreply.github.com>"]
license = "BSD-2-Clause"
description = "Macros for dhall"
readme = "README.md"
repository = "https://github.com/parzivale/dhall-rust"
edition = "2024"

[lib]
proc-macro = true
doctest = false

[dependencies]
quote = "1.0.47"
proc-macro2 = "1.0.107"
syn = "3.0.3"

[dev-dependencies]
version-sync = "0.9.5"

[lints]
workspace = true
